### ISSUE TITLE
Can you fix this?

### ISSUE THREAD

**Issue by askfriends** [jaskaranSM/megasdkrest#3]
I dont know if i should ask you but this is only option i have.
I am deploying this repo https://github.com/soffex/mirror-leech-telegram-bot to heroku via actions which uses your package in Dockerfile, i get following error, can u fix that?

` ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Added git remote heroku
Setting CONFIG_FILE_URL and restarting ***... done, v3
The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 127
 ▸    Error: docker build exited with Error: 127

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app *** 
The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 127
 ▸    Error: docker build exited with Error: 127

        
The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 127
Error: Error: Command failed: heroku container:push web --app *** 
The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 127
 ▸    Error: docker build exited with Error: 127

 ▸    Error: docker build exited with Error: 127`

**Comment by JaskaranSM** [comment]
Hi, I am afraid this question is not relevant for this repository, you should ask it in https://github.com/soffex/mirror-leech-telegram-bot , Also I have checked the Dockerfile, that base container is not mine, you should ask about that in aforementioned repo.

**Comment by askfriends** [comment]
> Hi, I am afraid this question is not relevant for this repository, you should ask it in https://github.com/soffex/mirror-leech-telegram-bot , Also I have checked the Dockerfile, that base container is not mine, you should ask about that in aforementioned repo.

ok bro thanks
